name: Deploy App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      # - uses: ruby/setup-ruby@v1
      #   with:
      #     bundler-cache: true

      - uses: actions/cache@v2
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Setup SSH Keys and known_hosts for fastlane match
        # Copied from https://github.com/maddox/actions/blob/master/ssh/entrypoint.sh
        run: |
          SSH_PATH="${HOME}/.ssh"

          mkdir -p "${SSH_PATH}"
          touch "${SSH_PATH}/known_hosts"

          echo "${PRIVATE_KEY}" > "${SSH_PATH}/id_rsa"

          chmod 700 "${SSH_PATH}"
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 600 "${SSH_PATH}/known_hosts"
          chmod 600 "${SSH_PATH}/id_rsa"

          eval $(ssh-agent)
          ssh-add "${SSH_PATH}/id_rsa"
        env:
          PRIVATE_KEY: ${{ secrets.MATCH_GIT_PRIVATE_KEY }}

      - name: Show macOS version
        run: |
          sw_vers

      - name: Show environment software versions
        run: |
          ruby --version
          bundler --version
          echo $HOME

      - name: Deploy App
        run: |
          # rm -rf vendor/bundle Pods
          bundle lock --add-platform x86_64-darwin-20
          make deploy
        env:
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
          APP_STORE_CONNECT_API_KEY_DURATION: ${{ secrets.APP_STORE_CONNECT_API_KEY_DURATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          PILOT_DISTRIBUTE_EXTERNAL: ${{ secrets.PILOT_DISTRIBUTE_EXTERNAL }}
          PILOT_SKIP_SUBMISSION: ${{ secrets.PILOT_SKIP_SUBMISSION }}
          PILOT_SKIP_WAITING_FOR_BUILD_PROCESSING: ${{ secrets.PILOT_SKIP_WAITING_FOR_BUILD_PROCESSING }}
